
name: Deploy

# on:
#   push:
#     branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t sanjay4051/githubactions
    - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin 
    - run: docker push sanjay4051/githubactions:latest
