name: Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  nginx-setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nginx
      run: |
        sudo apt update
        sudo apt install -y nginx

    - name: Start Nginx
      run: sudo systemctl start nginx

    - name: Check Nginx status
      run: sudo systemctl status nginx

    - name: Test Nginx is running
      run: curl -I http://localhost
